-- Create a retention list

WITH 
STANDALONE_RETENTION AS  
(
    SELECT  
        COUNT(DISTINCT B.MSISDN) RETENT_USER,   
        A.YEARMONTH YEARMONTH_1,  
        B.YEARMONTH YEARMONTH_2
    FROM 
        STANDALONE_MONTHLY A
    LEFT JOIN STANDALONE_MONTHLY B 
        ON A.MSISDN = B.MSISDN
    WHERE 1=1
        AND A.YEARMONTH <= B.YEARMONTH 
        AND A.YEARMONTH >= 202101 --AND B.YEARMONTH = 202208
    GROUP BY A.YEARMONTH, B.YEARMONTH 
), 

STANDALONE_TOTAL_COUNT AS  
(
    SELECT  
        COUNT(DISTINCT MSISDN) TOTAL_COUNT, 
        YEARMONTH 
    FROM 
        LIFEBOX_STANDALONE_MONTHLY 
    GROUP BY YEARMONTH
)

(SELECT 
    YEARMONTH_1, 
    YEARMONTH_2, 
    RETENT_USER, 
    TOTAL_COUNT, 
    ROUND((RETENT_USER/TOTAL_COUNT)*100 ,1) RATE 
FROM 
    STANDALONE_TOTAL_COUNT A, 
    STANDALONE_RETENTION B 
WHERE A.YEARMONTH=B.YEARMONTH_1)
ORDER BY YEARMONTH_1, YEARMONTH_2